stages:
  - test
  - build
  - deploy

# Job para rodar testes
realizar_testes:
  stage: test
  image: node:20.7.0-alpine3.17
  before_script:
    - cd app/
    - npm install
  script:
    - npm test
  only:
    - kubernetes-deploy

# Job para construir a imagem Docker
build_image:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  script:
    - docker build -t gcr.io/your-project-id/myapp:latest .
    - docker push gcr.io/your-project-id/myapp:latest
  only:
    - kubernetes-deploy

# Job para fazer o deploy no Kubernetes
deploy_kubernetes:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    - gcloud config set project your-project-id
    - gcloud container clusters get-credentials your-cluster --zone your-zone
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
  only:
    - kubernetes-deploy
